services:
  ollama:
    # image: ollama/ollama:0.1.29
    image: ollama/ollama:0.5.1
    # image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: corpdocgpt-backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: corpdocgpt-frontend
    ports:
      - "1420:1420"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data: